name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=ghcr.io/siacentral/sia-web-troubleshooter:buildcache
          cache-to: type=registry,ref=ghcr.io/siacentral/sia-web-troubleshooter:buildcache,mode=max
          tags: ghcr.io/siacentral/sia-web-troubleshooter:latest